### ISSUE TITLE
Attribute Error when trying to post a user

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3#1746]
When I try to post a user to `/principals/users` I get an error.

Posted resource:

```
{
  "content_type": "adhocracy_core.resources.principal.IUser",
  "data": {
    "adhocracy_core.sheets.principal.IPasswordAuthentication": {
      "password": "asdasd"
    },
    "adhocracy_core.sheets.principal.IUserBasic": {
      "name": "test"
    }
  }
}
```

Response:

```
{
  "status": "error",
  "errors": [{
    "location": "internal",
    "name": "",
    "description": "AttributeError: 'Pool' object has no attribute 'roles'; time: 2015-10-13 13:40:23,754"
  }]
}
```

Backend log:

```
2015-10-13 15:13:18,410 ERROR [adhocracy_core.rest.exceptions][MainThread] internal
Traceback (most recent call last):
  File "/home/tobib/a3/a3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tobib/a3/a3/eggs/pyramid_tm-0.11-py3.4.egg/pyramid_tm/__init__.py", line 94, in tm_tween
    reraise(*exc_info)
  File "/home/tobib/a3/a3/eggs/pyramid_tm-0.11-py3.4.egg/pyramid_tm/compat.py", line 15, in reraise
    raise value
  File "/home/tobib/a3/a3/eggs/pyramid_tm-0.11-py3.4.egg/pyramid_tm/__init__.py", line 75, in tm_tween
    response = handler(request)
  File "/home/tobib/a3/a3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/tobib/a3/a3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/home/tobib/a3/a3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "/home/tobib/a3/a3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/config/views.py", line 245, in _secured_view
    return view(context, request)
  File "/home/tobib/a3/a3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/home/tobib/a3/a3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/config/views.py", line 486, in _class_view
    inst = view(context, request)
  File "/home/tobib/a3/a3/src/adhocracy_core/adhocracy_core/rest/views.py", line 373, in __init__
    super().__init__(context, request)
  File "/home/tobib/a3/a3/src/adhocracy_core/adhocracy_core/rest/views.py", line 316, in __init__
    extra_validators=validators)
  File "/home/tobib/a3/a3/src/adhocracy_core/adhocracy_core/rest/views.py", line 138, in validate_request_data
    parent_pool=parent)
  File "/home/tobib/a3/a3/eggs/colander-1.0-py3.4.egg/colander/__init__.py", line 1989, in bind
    cloned._bind(kw)
  File "/home/tobib/a3/a3/eggs/colander-1.0-py3.4.egg/colander/__init__.py", line 1995, in _bind
    child._bind(kw)
  File "/home/tobib/a3/a3/eggs/colander-1.0-py3.4.egg/colander/__init__.py", line 2003, in _bind
    self.after_bind(self, kw)
  File "/home/tobib/a3/a3/src/adhocracy_core/adhocracy_core/rest/schemas.py", line 165, in add_post_data_subschemas
    node.add(schema.bind(**kw))
  File "/home/tobib/a3/a3/eggs/colander-1.0-py3.4.egg/colander/__init__.py", line 1989, in bind
    cloned._bind(kw)
  File "/home/tobib/a3/a3/eggs/colander-1.0-py3.4.egg/colander/__init__.py", line 1995, in _bind
    child._bind(kw)
  File "/home/tobib/a3/a3/eggs/colander-1.0-py3.4.egg/colander/__init__.py", line 2000, in _bind
    v = v(self, kw)
  File "/home/tobib/a3/a3/eggs/colander-1.0-py3.4.egg/colander/__init__.py", line 2139, in __call__
    return self.wrapped(node, kw)
  File "/home/tobib/a3/a3/src/adhocracy_core/adhocracy_core/sheets/principal.py", line 172, in deferred_roles_and_group_roles
    roles_and_group_roles = set(context.roles)
AttributeError: 'Pool' object has no attribute 'roles'
2015-10-13 15:13:18,411 WARNI [adhocracy_core.rest.exceptions][MainThread] 
Exception 500 in request POST http://localhost:6541/principals/users.
headers: {'Content-Type': 'application/json;charset=UTF-8', 'Dnt': '1', 'Accept-Language': 'de,en;q=0.8,en-US;q=0.6,fr;q=0.4,pt-BR;q=0.2,pt;q=0.2,zh;q=0.2,ar;q=0.2', 'Origin': 'http://localhost:6551', 'Pragma': 'no-cache', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36', 'Cache-Control': 'no-cache', 'Referer': 'http://localhost:6551/r/organisation/kiezkasse/', 'Accept': 'application/json, text/plain, */*', 'Content-Length': '209', 'X-User-Path': 'http://localhost:6541/principals/users/0000000/', 'Connection': 'keep-alive', 'X-User-Token': '<hidden>', 'Host': 'localhost:6541'}
body: {"content_type": "adhocracy_core.resources.principal.IUser", "data": {"adhocracy_core.sheets.principal.IPasswordAuthentication": {"password": "<hidden>"}, "adhocracy_core.sheets.principal.IUserBasic": {"name": "test"}}}
2015-10-13 15:13:18,412 WARNI [adhocracy_core.rest.exceptions][MainThread] ErrorEntry(location='internal', name='', description="AttributeError: 'Pool' object has no attribute 'roles'; time: 2015-10-13 13:40:23,754")
```

**Comment by pallix** [comment]
It seems to me that the `deferred_roles_and_group_roles` validator is called with the wrong context at least once, with `IUsersService` instead of `IUser`.

**Comment by xi** [comment]
Seems to work now.
