### ISSUE TITLE
Error when migrating a db from before the users catalog to after

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#1751]
I got an error when migrating a db created with a commit before the users catalog and doing the migration from a code version having the user indexes  to after:

```
git checkout 3ab6a8884a1ce877abff65e51c6282444c7ef0b5
# create a db
git checkout master
./bin/sd_evolve  --latest etc/development.ini
Executing evolution step adhocracy_core.evolution.lower_case_users_emails
2015-10-14 14:59:39,101 INFO  [adhocracy_core.evolution][MainThread] Running evolve step: Lower case users email.
Traceback (most recent call last):
  File "./bin/sd_evolve", line 117, in <module>
    sys.exit(substanced.scripts.evolve.main())
  File "/home/alphonse/projects/adhocracy3.mercator/src/substanced/substanced/scripts/evolve.py", line 83, in main
    complete = manager.evolve(latest)
  File "/home/alphonse/projects/adhocracy3.mercator/src/substanced/substanced/evolution/__init__.py", line 75, in evolve
    func(self.context)
  File "/home/alphonse/projects/adhocracy3.mercator/src/adhocracy_core/adhocracy_core/evolution/__init__.py", line 148, in logger_decorator
    func(*args, **kwargs)
  File "/home/alphonse/projects/adhocracy3.mercator/src/adhocracy_core/adhocracy_core/evolution/__init__.py", line 310, in lower_case_users_emails
    sheet.set({'email': user.email.lower()})
  File "/home/alphonse/projects/adhocracy3.mercator/src/adhocracy_core/adhocracy_core/sheets/__init__.py", line 172, in set
    self.registry.notify(event)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/pyramid-1.5.2-py3.5.egg/pyramid/registry.py", line 74, in notify
    [ _ for _ in self.subscribers(events, None) ]
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/zope.interface-4.1.2-py3.5-linux-x86_64.egg/zope/interface/registry.py", line 328, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/zope.interface-4.1.2-py3.5-linux-x86_64.egg/zope/interface/adapter.py", line 600, in subscribers
    subscription(*objects)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/pyramid-1.5.2-py3.5.egg/pyramid/config/adapters.py", line 130, in subscriber_wrapper
    return derived_subscriber(*arg)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/pyramid-1.5.2-py3.5.egg/pyramid/config/adapters.py", line 103, in derived_subscriber
    return subscriber(arg[0])
  File "/home/alphonse/projects/adhocracy3.mercator/src/adhocracy_core/adhocracy_core/catalog/subscriber.py", line 48, in reindex_user_email
    catalogs.reindex_index(event.object, 'private_user_email')
  File "/home/alphonse/projects/adhocracy3.mercator/src/adhocracy_core/adhocracy_core/catalog/__init__.py", line 46, in reindex_index
    raise KeyError(msg)
KeyError: 'catalog index private_user_email does not exist.'
```

**Comment by pallix** [comment]
This has been fixed in master since a good time.
