### ISSUE TITLE
Error when creating a new database

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#1767]
I got an error when deleting the database and creating a new database by restarting a3.

This is related to #1728 as setting `workers = 1` in  `etc/development.ini` solves the issue.

@slomo any idea?

```
[2015-10-15 14:09:41 +0200] [8206] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/gunicorn-19.2.1-py3.5.egg/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/gunicorn-19.2.1-py3.5.egg/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/gunicorn-19.2.1-py3.5.egg/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/gunicorn-19.2.1-py3.5.egg/gunicorn/app/wsgiapp.py", line 63, in load
    return self.load_pasteapp()
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/gunicorn-19.2.1-py3.5.egg/gunicorn/app/wsgiapp.py", line 59, in load_pasteapp
    return load_pasteapp(self.cfgurl, self.relpath, global_conf=None)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/gunicorn-19.2.1-py3.5.egg/gunicorn/app/pasterapp.py", line 71, in load_pasteapp
    global_conf=global_conf)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/PasteDeploy-1.5.2-py3.5.egg/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/PasteDeploy-1.5.2-py3.5.egg/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/PasteDeploy-1.5.2-py3.5.egg/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/PasteDeploy-1.5.2-py3.5.egg/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/PasteDeploy-1.5.2-py3.5.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/alphonse/projects/adhocracy3.mercator/src/adhocracy_mercator/adhocracy_mercator/__init__.py", line 26, in main
    app = config.make_wsgi_app()
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/pyramid-1.5.2-py3.5.egg/pyramid/config/__init__.py", line 951, in make_wsgi_app
    self.registry.notify(ApplicationCreated(app))
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/pyramid-1.5.2-py3.5.egg/pyramid/registry.py", line 74, in notify
    [ _ for _ in self.subscribers(events, None) ]
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/zope.interface-4.1.2-py3.5-linux-x86_64.egg/zope/interface/registry.py", line 328, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/zope.interface-4.1.2-py3.5-linux-x86_64.egg/zope/interface/adapter.py", line 600, in subscribers
    subscription(*objects)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/pyramid-1.5.2-py3.5.egg/pyramid/config/adapters.py", line 103, in derived_subscriber
    return subscriber(arg[0])
  File "/home/alphonse/projects/adhocracy3.mercator/src/substanced/substanced/catalog/subscribers.py", line 138, in on_startup
    root = app.root_factory(request)
  File "/home/alphonse/projects/adhocracy3.mercator/src/adhocracy_core/adhocracy_core/__init__.py", line 26, in root_factory
    _set_app_root_if_missing(request)
  File "/home/alphonse/projects/adhocracy3.mercator/src/adhocracy_core/adhocracy_core/__init__.py", line 43, in _set_app_root_if_missing
    transaction.commit()
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/transaction-1.4.3-py3.5.egg/transaction/_manager.py", line 111, in commit
    return self.get().commit()
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/transaction-1.4.3-py3.5.egg/transaction/_transaction.py", line 280, in commit
    reraise(t, v, tb)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/transaction-1.4.3-py3.5.egg/transaction/_compat.py", line 55, in reraise
    raise value
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/transaction-1.4.3-py3.5.egg/transaction/_transaction.py", line 271, in commit
    self._commitResources()
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/transaction-1.4.3-py3.5.egg/transaction/_transaction.py", line 417, in _commitResources
    reraise(t, v, tb)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/transaction-1.4.3-py3.5.egg/transaction/_compat.py", line 55, in reraise
    raise value
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/transaction-1.4.3-py3.5.egg/transaction/_transaction.py", line 394, in _commitResources
    rm.tpc_vote(self)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/ZODB-4.1.0-py3.5.egg/ZODB/Connection.py", line 788, in tpc_vote
    s = vote(transaction)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/ZEO-4.1.0-py3.5.egg/ZEO/ClientStorage.py", line 1107, in tpc_vote
    return self._check_serials()
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/ZEO-4.1.0-py3.5.egg/ZEO/ClientStorage.py", line 937, in _check_serials
    raise s
ZODB.POSException.ConflictError: database conflict error (oid 0x00, class persistent.mapping.PersistentMapping, serial this txn started with 0x03b270799cd35555, serial currently committed 0x03b27079aee471cc)
Traceback (most recent call last):
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/gunicorn-19.2.1-py3.5.egg/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/gunicorn-19.2.1-py3.5.egg/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/gunicorn-19.2.1-py3.5.egg/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/gunicorn-19.2.1-py3.5.egg/gunicorn/app/wsgiapp.py", line 63, in load
    return self.load_pasteapp()
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/gunicorn-19.2.1-py3.5.egg/gunicorn/app/wsgiapp.py", line 59, in load_pasteapp
    return load_pasteapp(self.cfgurl, self.relpath, global_conf=None)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/gunicorn-19.2.1-py3.5.egg/gunicorn/app/pasterapp.py", line 71, in load_pasteapp
    global_conf=global_conf)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/PasteDeploy-1.5.2-py3.5.egg/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/PasteDeploy-1.5.2-py3.5.egg/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/PasteDeploy-1.5.2-py3.5.egg/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/PasteDeploy-1.5.2-py3.5.egg/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/PasteDeploy-1.5.2-py3.5.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/alphonse/projects/adhocracy3.mercator/src/adhocracy_mercator/adhocracy_mercator/__init__.py", line 26, in main
    app = config.make_wsgi_app()
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/pyramid-1.5.2-py3.5.egg/pyramid/config/__init__.py", line 951, in make_wsgi_app
    self.registry.notify(ApplicationCreated(app))
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/pyramid-1.5.2-py3.5.egg/pyramid/registry.py", line 74, in notify
    [ _ for _ in self.subscribers(events, None) ]
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/zope.interface-4.1.2-py3.5-linux-x86_64.egg/zope/interface/registry.py", line 328, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/zope.interface-4.1.2-py3.5-linux-x86_64.egg/zope/interface/adapter.py", line 600, in subscribers
    subscription(*objects)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/pyramid-1.5.2-py3.5.egg/pyramid/config/adapters.py", line 103, in derived_subscriber
    return subscriber(arg[0])
  File "/home/alphonse/projects/adhocracy3.mercator/src/substanced/substanced/catalog/subscribers.py", line 138, in on_startup
    root = app.root_factory(request)
  File "/home/alphonse/projects/adhocracy3.mercator/src/adhocracy_core/adhocracy_core/__init__.py", line 26, in root_factory
    _set_app_root_if_missing(request)
  File "/home/alphonse/projects/adhocracy3.mercator/src/adhocracy_core/adhocracy_core/__init__.py", line 43, in _set_app_root_if_missing
    transaction.commit()
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/transaction-1.4.3-py3.5.egg/transaction/_manager.py", line 111, in commit
    return self.get().commit()
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/transaction-1.4.3-py3.5.egg/transaction/_transaction.py", line 280, in commit
    reraise(t, v, tb)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/transaction-1.4.3-py3.5.egg/transaction/_compat.py", line 55, in reraise
    raise value
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/transaction-1.4.3-py3.5.egg/transaction/_transaction.py", line 271, in commit
    self._commitResources()
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/transaction-1.4.3-py3.5.egg/transaction/_transaction.py", line 417, in _commitResources
    reraise(t, v, tb)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/transaction-1.4.3-py3.5.egg/transaction/_compat.py", line 55, in reraise
    raise value
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/transaction-1.4.3-py3.5.egg/transaction/_transaction.py", line 394, in _commitResources
    rm.tpc_vote(self)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/ZODB-4.1.0-py3.5.egg/ZODB/Connection.py", line 788, in tpc_vote
    s = vote(transaction)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/ZEO-4.1.0-py3.5.egg/ZEO/ClientStorage.py", line 1107, in tpc_vote
    return self._check_serials()
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/ZEO-4.1.0-py3.5.egg/ZEO/ClientStorage.py", line 937, in _check_serials
    raise s
ZODB.POSException.ConflictError: database conflict error (oid 0x00, class persistent.mapping.PersistentMapping, serial this txn started with 0x03b270799cd35555, serial currently committed 0x03b27079aee471cc)
[2015-10-15 14:09:41 +0200] [8206] [INFO] Worker exiting (pid: 8206)
.
...
.
...
[2015-10-15 14:10:11 +0200] [8197] [INFO] Shutting down: Master
[2015-10-15 14:10:11 +0200] [8197] [INFO] Reason: Worker failed to boot.
```

**Comment by xi** [comment]
I recerntly recreated my database and did not have a problem (mercator build).

**Comment by pallix** [comment]
I hope it's not linked to python 3.5

**Comment by pallix** [comment]
I got the same problem with the buildout compiled version of python 3.4

**Comment by joka** [comment]
> I got the same problem with the buildout compiled version of python 3.4

This looks more like different python threads want to create the same adhocracyc root object.

**Comment by joka** [comment]
@pallix can you reproduce this somehow?

**Comment by pallix** [comment]
I cannot reproduce it anymore, I'm using a  different python now, python 3.4.3 with pyenv.

I'm closing the issue and will reopen it if I encounter the bug again.
