### ISSUE TITLE
Migration error on staging mercator

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#2173]
When migrating the staging db locally, I got this error:

```
sd_evolve  --latest etc/development.ini
2016-03-21 16:11:03,906 INFO  [ZEO.ClientStorage][MainThread] ('localhost', 9963) ClientStorage (pid=30520) created RW/normal for storage: 'main'
2016-03-21 16:11:03,908 INFO  [ZEO.cache][MainThread] created temporary cache file 5
2016-03-21 16:11:03,913 INFO  [ZEO.ClientStorage][Connect([(<AddressFamily.AF_INET: 2>, ('localhost', 9963))])] ('localhost', 9963) Testing connection <ManagedClientConnection ('127.0.0.1', 9963)>
2016-03-21 16:11:03,913 INFO  [ZEO.zrpc.Connection(b'C')][('localhost', 9963) zeo client networking thread] (127.0.0.1:9963) received handshake b'Z3101'
2016-03-21 16:11:04,014 INFO  [ZEO.ClientStorage][Connect([(<AddressFamily.AF_INET: 2>, ('localhost', 9963))])] ('localhost', 9963) Server authentication protocol None
2016-03-21 16:11:04,014 INFO  [ZEO.ClientStorage][Connect([(<AddressFamily.AF_INET: 2>, ('localhost', 9963))])] ('localhost', 9963) Connected to storage: ('localhost.localdomain', 9963)
2016-03-21 16:11:04,015 INFO  [ZEO.ClientStorage][Connect([(<AddressFamily.AF_INET: 2>, ('localhost', 9963))])] ('localhost', 9963) No verification necessary -- empty cache
2016-03-21 16:11:04,021 INFO  [ZEO.ClientStorage][MainThread] ('localhost', 9964) ClientStorage (pid=30520) created RW/normal for storage: 'main'
2016-03-21 16:11:04,021 INFO  [ZEO.cache][MainThread] created temporary cache file 10
2016-03-21 16:11:04,022 WARNI [ZEO.zrpc][Connect([(<AddressFamily.AF_INET: 2>, ('localhost', 9964))])] (30520) CW: error connecting to ('::1', 9964): ECONNREFUSED
2016-03-21 16:11:04,022 INFO  [ZEO.ClientStorage][Connect([(<AddressFamily.AF_INET: 2>, ('localhost', 9964))])] ('localhost', 9964) Testing connection <ManagedClientConnection ('127.0.0.1', 9964)>
2016-03-21 16:11:04,023 INFO  [ZEO.zrpc.Connection(b'C')][('localhost', 9964) zeo client networking thread] (127.0.0.1:9964) received handshake b'Z3101'
2016-03-21 16:11:04,123 INFO  [ZEO.ClientStorage][Connect([(<AddressFamily.AF_INET: 2>, ('localhost', 9964))])] ('localhost', 9964) Server authentication protocol None
2016-03-21 16:11:04,124 INFO  [ZEO.ClientStorage][Connect([(<AddressFamily.AF_INET: 2>, ('localhost', 9964))])] ('localhost', 9964) Connected to storage: ('localhost.localdomain', 9964)
2016-03-21 16:11:04,125 INFO  [ZEO.ClientStorage][Connect([(<AddressFamily.AF_INET: 2>, ('localhost', 9964))])] ('localhost', 9964) No verification necessary -- empty cache
2016-03-21 16:11:04,264 DEBUG [adhocracy_core.messaging][MainThread] Messenger will use mail queue: True
2016-03-21 16:11:04,301 DEBUG [adhocracy_core.websockets.client][Thread-1] Try connecting to the Websocket server at ws://localhost:6561
2016-03-21 16:11:04,303 DEBUG [adhocracy_core.websockets.client][Thread-1] Connected to the Websocket server
2016-03-21 16:11:04,607 WARNI [substanced.catalog.subscribers][MainThread] Cannot autosync/autoreindex catalog due to unfinished evolve steps
Executing evolution step adhocracy_core.evolution.add_workflow_assignment_sheet_to_pools_simples
2016-03-21 16:11:04,608 INFO  [adhocracy_core.evolution][MainThread] Running evolve step: Add generic workflow sheet to pools and simples.
Traceback (most recent call last):
  File "/home/alphonse/projects/adhocracy3/bin/sd_evolve", line 125, in <module>
    sys.exit(substanced.scripts.evolve.main())
  File "/home/alphonse/projects/adhocracy3/src/substanced/substanced/scripts/evolve.py", line 83, in main
    complete = manager.evolve(latest)
  File "/home/alphonse/projects/adhocracy3/src/substanced/substanced/evolution/__init__.py", line 75, in evolve
    func(self.context)
  File "/home/alphonse/projects/adhocracy3/src/adhocracy_core/adhocracy_core/evolution/__init__.py", line 157, in logger_decorator
    func(*args, **kwargs)
  File "/home/alphonse/projects/adhocracy3/src/adhocracy_core/adhocracy_core/evolution/__init__.py", line 352, in add_workflow_assignment_sheet_to_pools_simples
    migrate_new_sheet(root, IPool, IWorkflowAssignment)
  File "/home/alphonse/projects/adhocracy3/src/adhocracy_core/adhocracy_core/evolution/__init__.py", line 99, in migrate_new_sheet
    resources = catalogs.search(query).elements
  File "/home/alphonse/projects/adhocracy3/src/adhocracy_core/adhocracy_core/catalog/__init__.py", line 60, in search
    count = len(sorted_elements)
ValueError: __len__() should return >= 0
```

With the debugger we can see that the catalog search encounters a `memory error`.

**Comment by pallix** [comment]
@joka any idea?

**Comment by joka** [comment]
> @joka any idea?

öh, no, Can I reproduce this with the staging database?

**Comment by pallix** [comment]
Yes, I just copied it yesterday and tried the migration from the master branch

**Comment by joka** [comment]
> Yes, I just copied it yesterday and tried the migration from the master branch

The staging server has no free memor left, I try the migration at my local computer  first.

**Comment by joka** [comment]
I guess we can close this.
