### ISSUE TITLE
Unicode not supported in YAML permissions files

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#2203]
There was a problem in the root permission yaml file on deployment. 
The words “deleted” and “hidden” were quoted with unicode quotations marks and the pyramid renderer tried to decoded them as ASCII.

Temporary fixed by #2202.

```
    Traceback (most recent call last):
                    File "bin/sd_evolve", line 11, in <module>
                      sys.exit(main())
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/substanced/scripts/evolve.py", line 76, in main
                      env = bootstrap(config_uri)
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/pyramid/paster.py", line 131, in bootstrap
                      app = get_app(config_uri, options=options)
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/pyramid/paster.py", line 31, in get_app
                      global_conf=options)
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
                      return loadobj(APP, uri, name=name, **kw)
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
                      return context.create()
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/paste/deploy/loadwsgi.py", line 710, in create
                      return self.object_type.invoke(self)
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
                      return fix_call(context.object, context.global_conf, **context.local_conf)
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/paste/deploy/util.py", line 55, in fix_call
                      val = callable(*args, **kw)
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/adhocracy_euth/__init__.py", line 23, in main
                      return config.make_wsgi_app()
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/pyramid/config/__init__.py", line 995, in make_wsgi_app
                      self.registry.notify(ApplicationCreated(app))
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/pyramid/registry.py", line 91, in notify
                      [ _ for _ in self.subscribers(events, None) ]
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/zope/interface/registry.py", line 328, in subscribers
                      return self.adapters.subscribers(objects, provided)
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/zope/interface/adapter.py", line 600, in subscribers
                      subscription(*objects)
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/pyramid/config/adapters.py", line 103, in derived_subscriber
                      return subscriber(arg[0])
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/adhocracy_core/authorization/__init__.py", line 177, in set_acms_for_app_root
                      acl += _get_root_base_acl()
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/adhocracy_core/authorization/__init__.py", line 187, in _get_root_base_acl
                      cstruct = render(root_acm_asset, {})
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/pyramid/renderers.py", line 81, in render
                      result = helper.render(value, None, request=request)
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/pyramid/renderers.py", line 469, in render
                      result = renderer(value, system_values)
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/adhocracy_core/renderers/__init__.py", line 28, in __call__
                      appstruct = safe_load(f)
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/yaml/__init__.py", line 94, in safe_load
                      return load(stream, SafeLoader)
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/yaml/__init__.py", line 70, in load
                      loader = Loader(stream)
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/yaml/loader.py", line 24, in __init__
                      Reader.__init__(self, stream)
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/yaml/reader.py", line 85, in __init__
                      self.determine_encoding()
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/yaml/reader.py", line 124, in determine_encoding
                      self.update_raw()
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/yaml/reader.py", line 178, in update_raw
                      data = self.stream.read(size)
                    File "/home/adhocracy3/adhocracy3/lib/python3.4/encodings/ascii.py", line 26, in decode
                      return codecs.ascii_decode(input, self.errors)[0]
                  UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1039: ordinal not in range(128)
```

**Comment by pallix** [comment]
Download `adhocracy_core-0.4.10.post286-py3-none-any.whl` and unzipping it, we can see that `root_permissions.yaml` is recognized as ASCII instead of Unicode

**Comment by pallix** [comment]
Building the wheel locally does not produce the error: 

Unzipping `adhocracy3/parts/wheels/adhocracy_core-0.4.10.post280-py3-none-any.whl` and checking the file encoding:

```
file ./authorization/root_permissions.yaml
./authorization/root_permissions.yaml: UTF-8 Unicode text
```

**Comment by pallix** [comment]
The file is maybe checkout incorrectly (?)

```
yves@liqd-build-dev-guest36:~$ file builds/adhocracy3/src/adhocracy_core/adhocracy_core/authorization/root_permissions.yaml 
builds/adhocracy3/src/adhocracy_core/adhocracy_core/authorization/root_permissions.yaml: ASCII text
```

**Comment by pallix** [comment]
```
yves@liqd-build-dev-guest36:/tmp$ git clone https://github.com/liqd/adhocracy3.mercator.git
Cloning into 'adhocracy3.mercator'...
remote: Counting objects: 134434, done.
remote: Compressing objects: 100% (250/250), done.
remote: Total 134434 (delta 136), reused 1 (delta 1), pack-reused 134181
Receiving objects: 100% (134434/134434), 22.39 MiB | 3.80 MiB/s, done.
Resolving deltas: 100% (98228/98228), done.
Checking connectivity... done.
yves@liqd-build-dev-guest36:/tmp$ cd ad
ad/                                             adhocracy3.mercator/                            adhocracy_core-0.4.10.post286-py3-none-any.whl
yves@liqd-build-dev-guest36:/tmp$ cd adhocracy3.mercator/
yves@liqd-build-dev-guest36:/tmp/adhocracy3.mercator$ file src/adhocracy_core/adhocracy_core/auth
authentication/ authorization/  
yves@liqd-build-dev-guest36:/tmp/adhocracy3.mercator$ file src/adhocracy_core/adhocracy_core/authorization/root_permissions.yaml 
src/adhocracy_core/adhocracy_core/authorization/root_permissions.yaml: ASCII text
```

Well git cloning locally with ssh or http also lead to ASCII:

```
> file src/adhocracy_core/adhocracy_core/authorization/root_permissions.yaml 
src/adhocracy_core/adhocracy_core/authorization/root_permissions.yaml: ASCII text
```

It's strange because my old local copy is in UTF-8

**Comment by pallix** [comment]
Humm probably it's everything in the ASCII subset of UTF8

**Comment by pallix** [comment]
I tried building the version that still contained unicode characters in yaml file, unzipped the built wheel, and it is correctly UTF8:

```
file ./adhocracy_core/authorization/root_permissions.yaml
./adhocracy_core/authorization/root_permissions.yaml: UTF-8 Unicode text
```

So no idea where the error comes from.

**Comment by 2e2a** [comment]
Unicode not needed in permission files.
