### ISSUE TITLE
Backend startup fails due to missing locale in substanced

### ISSUE THREAD

**Issue by slomo** [liqd/adhocracy3#445]
While setting up the staging server I experienced the following problem after starting the backend

```
Traceback (most recent call last):                                                                                                                                                            [50/1904]
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 63, in load
    return self.load_pasteapp()
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 59, in load_pasteapp
    return load_pasteapp(self.cfgurl, self.relpath, global_conf=None)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/gunicorn/app/pasterapp.py", line 73, in load_pasteapp
    global_conf=global_conf)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/adhocracy_mercator/__init__.py", line 26, in main
    includeme(config)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/adhocracy_mercator/__init__.py", line 13, in includeme
    config.include('adhocracy_core')
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/pyramid/config/__init__.py", line 755, in include
    c(configurator)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/adhocracy_core/__init__.py", line 71, in includeme
    config.include('.catalog')
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/pyramid/config/__init__.py", line 755, in include
    c(configurator)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/adhocracy_core/catalog/__init__.py", line 40, in includeme
    config.scan('substanced.catalog')
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/pyramid/config/__init__.py", line 930, in scan
    ignore=ignore)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/venusian/__init__.py", line 205, in scan
    __import__(modname)
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/substanced/catalog/views/catalog.py", line 16, in <module>
    from substanced.sdi import mgmt_view
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/substanced/sdi/__init__.py", line 49, in <module>
    from ..principal import DefaultUserLocator
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/substanced/principal/__init__.py", line 312, in <module>
    _LOCALES = get_locales()
  File "/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/substanced/principal/__init__.py", line 309, in get_locales
    '..', 'locale'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/adhocracy3/adhocracy3/lib/python3.4/site-packages/substanced/principal/../locale'
```
@joka concluded that this occurs in conjunction with the generation of the admin interface

Current quick fix is to create that folder.

**Comment by 2e2a** [comment]
Did not occur when setting up the new demo platform.
