### ISSUE TITLE
registration triggers error in log file

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3#451]
I just tried to register a new user on my local development system. I got two errors in the UI and the following backend log. Dispite of these issues, I was able to activate my account and log in without issues.

```
2015-01-05 17:32:57,354 DEBUG [adhocracy_core.resources.principal][MainThread] Sending registration mail to sdf@sdf.sdf for new user named sdf, activation path=/activate/hCkwESvgfzFz7P1qgGvskI0Y
2015-01-05 17:32:57,455 DEBUG [adhocracy_core.websockets.client][MainThread] Sending message to Websocket server: {"resource": "/principals/users/0000003", "event": "created"}
2015-01-05 17:32:57,457 ERROR [txn.140135284180736][MainThread] Error in abort() on manager <repoze.sendmail.delivery.MailDataManager object at 0x7f73be3502e8>
Traceback (most recent call last):
  File "/home/tobib/a3/a3/eggs/transaction-1.4.3-py3.4.egg/transaction/_transaction.py", line 374, in _callAfterCommitHooks
    rm.abort(self)
  File "/home/tobib/a3/a3/eggs/repoze.sendmail-4.2-py3.4.egg/repoze/sendmail/delivery.py", line 119, in abort
    raise ValueError("TPC in progress")
ValueError: TPC in progress
2015-01-05 17:32:57,466 WARNI [adhocracy_core.rest.views][MainThread] Found 2 validation errors in request: <b'{"content_type":"adhocracy_core.resources.principal.IUser","data":{"adhocracy_core.sheets.principal.IUserBasic":{"name":"sdf","email":"sdf@sdf.sdf"},"adhocracy_core.sheets.principal.IPasswordAuthentication":{"password":"sdfsdf"}}}'>
2015-01-05 17:32:57,466 WARNI [adhocracy_core.rest.views][MainThread]   {'description': 'The user login name is not unique', 'name': 'data.adhocracy_core.sheets.principal.IUserBasic.name', 'location': 'body'}
2015-01-05 17:32:57,467 WARNI [adhocracy_core.rest.views][MainThread]   {'description': 'The user login email is not unique', 'name': 'data.adhocracy_core.sheets.principal.IUserBasic.email', 'location': 'body'}
```

**Comment by joka** [comment]
> I don't want to close this since the "TPC in progress" error in the logs is ugly in any case. @joka maybe you have an idea?

no, i  would wait or fix repoze.sendmail

**Comment by xi** [comment]
Has not happened again since then. Closing.

**Comment by xi** [comment]
Just saw that we are still waiting for a fix in repoze.sendmail. Reopening.
